/*ACTUALIZANDO BASE LEGAL     BL-0001866 */


/*ACTUALIZANDO BASE LEGAL*/
UPDATE 
NPS_INTEGRADO.PGH_BASE_LEGAL BL
SET
BL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
BL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001866');


/*ACTUALIZANDO DETALLE BASE LEGAL*/
UPDATE
NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL
SET
DBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
DBL.ID_DETALLE_BASE_LEGAL = (SELECT MIN(DBL.ID_DETALLE_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL WHERE  DBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001866'));

/*ACTUALIZANDO LISTA DE CONCORDANCIAS*/
UPDATE
NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL
SET
LBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
LBL.ID_LISTADO_BASE_LEGAL IN (SELECT LBL.ID_LISTADO_BASE_LEGAL FROM NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL WHERE LBL.ID_PADRE IS NULL AND LBL.COD_ACCION IS NULL AND LBL.ID_BASE_LEGAL_ORI = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001866'));


/*ACTUALIZANDO LISTA DE OBLIGACIONES*/
UPDATE
NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL
SET
OBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
OBL.ID_OBL_BASE IN (SELECT OBL.ID_OBL_BASE FROM NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL WHERE OBL.ID_PADRE IS NULL AND OBL.COD_ACCION IS NULL AND OBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001866'));




/*ACTUALIZANDO BASE LEGAL     BL-0001012 */


/*ACTUALIZANDO BASE LEGAL*/
UPDATE 
NPS_INTEGRADO.PGH_BASE_LEGAL BL
SET
BL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
BL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001012');


/*ACTUALIZANDO DETALLE BASE LEGAL*/
UPDATE
NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL
SET
DBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
DBL.ID_DETALLE_BASE_LEGAL = (SELECT MIN(DBL.ID_DETALLE_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL WHERE  DBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001012'));

/*ACTUALIZANDO LISTA DE CONCORDANCIAS*/
UPDATE
NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL
SET
LBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
LBL.ID_LISTADO_BASE_LEGAL IN (SELECT LBL.ID_LISTADO_BASE_LEGAL FROM NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL WHERE LBL.ID_PADRE IS NULL AND LBL.COD_ACCION IS NULL AND LBL.ID_BASE_LEGAL_ORI = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001012'));


/*ACTUALIZANDO LISTA DE OBLIGACIONES*/
UPDATE
NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL
SET
OBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
OBL.ID_OBL_BASE IN (SELECT OBL.ID_OBL_BASE FROM NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL WHERE OBL.ID_PADRE IS NULL AND OBL.COD_ACCION IS NULL AND OBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001012'));






/*ACTUALIZANDO BASE LEGAL     BL-0002015 */

/*ACTUALIZANDO BASE LEGAL*/
UPDATE 
NPS_INTEGRADO.PGH_BASE_LEGAL BL
SET
BL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
BL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0002015');


/*ACTUALIZANDO DETALLE BASE LEGAL*/
UPDATE
NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL
SET
DBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
DBL.ID_DETALLE_BASE_LEGAL = (SELECT MIN(DBL.ID_DETALLE_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL WHERE  DBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0002015'));

/*ACTUALIZANDO LISTA DE CONCORDANCIAS*/
UPDATE
NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL
SET
LBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
LBL.ID_LISTADO_BASE_LEGAL IN (SELECT LBL.ID_LISTADO_BASE_LEGAL FROM NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL WHERE LBL.ID_PADRE IS NULL AND LBL.COD_ACCION IS NULL AND LBL.ID_BASE_LEGAL_ORI = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0002015'));


/*ACTUALIZANDO LISTA DE OBLIGACIONES*/
UPDATE
NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL
SET
OBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
OBL.ID_OBL_BASE IN (SELECT OBL.ID_OBL_BASE FROM NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL WHERE OBL.ID_PADRE IS NULL AND OBL.COD_ACCION IS NULL AND OBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0002015'));






/*ACTUALIZANDO BASE LEGAL     BL-0000429 */


/*ACTUALIZANDO BASE LEGAL*/
UPDATE 
NPS_INTEGRADO.PGH_BASE_LEGAL BL
SET
BL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
BL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0000429');


/*ACTUALIZANDO DETALLE BASE LEGAL*/
UPDATE
NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL
SET
DBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
DBL.ID_DETALLE_BASE_LEGAL = (SELECT MIN(DBL.ID_DETALLE_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL WHERE  DBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0000429'));

/*ACTUALIZANDO LISTA DE CONCORDANCIAS*/
UPDATE
NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL
SET
LBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
LBL.ID_LISTADO_BASE_LEGAL IN (SELECT LBL.ID_LISTADO_BASE_LEGAL FROM NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL WHERE LBL.ID_PADRE IS NULL AND LBL.COD_ACCION IS NULL AND LBL.ID_BASE_LEGAL_ORI = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0000429'));


/*ACTUALIZANDO LISTA DE OBLIGACIONES*/
UPDATE
NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL
SET
OBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
OBL.ID_OBL_BASE IN (SELECT OBL.ID_OBL_BASE FROM NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL WHERE OBL.ID_PADRE IS NULL AND OBL.COD_ACCION IS NULL AND OBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0000429'));





/*ACTUALIZANDO BASE LEGAL     BL-0001976 */


/*ACTUALIZANDO BASE LEGAL*/
UPDATE 
NPS_INTEGRADO.PGH_BASE_LEGAL BL
SET
BL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
BL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001976');


/*ACTUALIZANDO DETALLE BASE LEGAL*/
UPDATE
NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL
SET
DBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
DBL.ID_DETALLE_BASE_LEGAL = (SELECT MIN(DBL.ID_DETALLE_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_DETALLE_BASE_LEGAL DBL WHERE  DBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001976'));

/*ACTUALIZANDO LISTA DE CONCORDANCIAS*/
UPDATE
NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL
SET
LBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
LBL.ID_LISTADO_BASE_LEGAL IN (SELECT LBL.ID_LISTADO_BASE_LEGAL FROM NPS_INTEGRADO.PGH_LISTADO_BASE_LEGAL LBL WHERE LBL.ID_PADRE IS NULL AND LBL.COD_ACCION IS NULL AND LBL.ID_BASE_LEGAL_ORI = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001976'));


/*ACTUALIZANDO LISTA DE OBLIGACIONES*/
UPDATE
NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL
SET
OBL.ESTADO = '1',TERMINAL_ACTUALIZACION='MIGRACION',USUARIO_ACTUALIZACION='MIGRACION',FECHA_ACTUALIZACION=SYSDATE
WHERE
OBL.ID_OBL_BASE IN (SELECT OBL.ID_OBL_BASE FROM NPS_INTEGRADO.PGH_OBLIGACION_BASE_LEGAL OBL WHERE OBL.ID_PADRE IS NULL AND OBL.COD_ACCION IS NULL AND OBL.ID_BASE_LEGAL = (SELECT MIN(BL.ID_BASE_LEGAL) FROM NPS_INTEGRADO.PGH_BASE_LEGAL BL WHERE BL.CODIGO_BASE_LEGAL = 'BL-0001976'));



update
PGH_CONF_OBLIGACION o
set
o.id_obligacion_tipo = 4
where
o.id_conf_obligacion
in
(
SELECT o.id_conf_obligacion FROM PGH_CONF_OBLIGACION O WHERE O.ESTADO = '1' AND O.ID_ACTIVIDAD = 1843 AND O.ID_PROCESO = 2 and id_obligacion_tipo = 27
);

update pgh_proceso_obligacion_tipo
set 
    id_obligacion_tipo = 4
where 
    id_obligacion_tipo = 27
    and id_actividad = 1843
    and id_proceso = 2
    and id_pro_obl_tip = 36;
