
-- MDI_MAESTRO_TABLA 

insert into MDI_MAESTRO_TABLA (DESCRIPCION, DOMINIO, USUARIO_ACTUALIZACION, USUARIO_CREACION, FECHA_CREACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, ES_EDITABLE, APLICACION)
values ('MEDIDA SEGURIDAD', 'MEDIDA_SEGURIDAD', '', 'squito', SYSDATE, null, '', '11.160.123.73', 'SI', 'MYC');

insert into MDI_MAESTRO_TABLA (DESCRIPCION, DOMINIO, USUARIO_ACTUALIZACION, USUARIO_CREACION, FECHA_CREACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, ES_EDITABLE, APLICACION)
values ('ESCENARIO MEDIDA', 'ESCENARIO_MEDIDA', '', 'squito', SYSDATE, null, '', '11.160.123.73', 'SI', 'MYC');

insert into MDI_MAESTRO_TABLA (DESCRIPCION, DOMINIO, USUARIO_ACTUALIZACION, USUARIO_CREACION, FECHA_CREACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, ES_EDITABLE, APLICACION)
values ('ACCION MEDIDA', 'ACCION_MEDIDA', '', 'squito', SYSDATE, null, '', '11.160.123.73', 'SI', 'MYC');


-- ACTUALIZAR MAESTRO_TABLA NUMERO DE ANEXO
UPDATE mdi_maestro_columna MC
SET MC.CODIGO='TA004'
WHERE MC.CODIGO=004  AND MC.ESTADO=1 AND MC.DESCRIPCION='ANEXO';

-- MDI_MAESTRO_TABLA NUMERO DE ANEXO
insert into MDI_MAESTRO_TABLA (DESCRIPCION, DOMINIO, USUARIO_ACTUALIZACION, USUARIO_CREACION, FECHA_CREACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, ES_EDITABLE, APLICACION)
values ('NUMERO DE ANEXO PROCEDIMIENTO', 'TA001', '', 'squito', SYSDATE, null, '', '11.160.123.73', 'SI', 'OBLIGACIONES');

insert into MDI_MAESTRO_TABLA (DESCRIPCION, DOMINIO, USUARIO_ACTUALIZACION, USUARIO_CREACION, FECHA_CREACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, ES_EDITABLE, APLICACION)
values ('NUMERO DE ANEXO REGLAMENTO', 'TA002', '', 'squito', SYSDATE, null, '', '11.160.123.73', 'SI', 'OBLIGACIONES');

insert into MDI_MAESTRO_TABLA (DESCRIPCION, DOMINIO, USUARIO_ACTUALIZACION, USUARIO_CREACION, FECHA_CREACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, ES_EDITABLE, APLICACION)
values ('NUMERO DE ANEXO ', 'TA004', '', 'squito', SYSDATE, null, '', '11.160.123.73', 'SI', 'OBLIGACIONES');

insert into MDI_MAESTRO_TABLA (DESCRIPCION, DOMINIO, USUARIO_ACTUALIZACION, USUARIO_CREACION, FECHA_CREACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, ES_EDITABLE, APLICACION)
values ('NUMERO DE ANEXO TEXTO UNICO', 'TA003', '', 'squito', SYSDATE, null, '', '11.160.123.73', 'SI', 'OBLIGACIONES');



--mdi_maestro_columna ESCENARIO_MEDIDA

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('AUMENTO DE TANQUES DE ALMACENAMIENTO', 'AA1', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('REEMPLAZO, REUBICACION O MODIFICACION DE LOS TANQUES DE ALMACENAMIENTO', 'AA2', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('AUMENTO O REUBICACION DE SURTIDORES O DISPENSADORES DE DESPACHO', 'AA3', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('NO CUENTA CON INFORME TECNICO FAVORABLE DE MODIFICACION', 'AA4', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('NO CUENTA CON MODIFICACION DE REGISTRO DE HIDROCARBUROS', 'AA5', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('UN MÍNIMO DE DOS (02) EXTINTORES CONTRAINCENDIOS', 'AA6', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES DEBIDAMENTE OPERATIVOS Y VIGENTES', 'AA7', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES DE POLVO QUÍMICO SECO MULTIPROPÓSITO ABC', 'AA8', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES CON RATING NO MENOR A 20 A: 80 B:C', 'AA9', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES CON CERTIFICACION UL O FM', 'AA10', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES UBICADOS EN LUGARES VISIBLES Y DE FACIL ACCESO', 'AA11', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

--mdi_maestro_columna MEDIDA_SEGURIDAD

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('CIERRE DE INSTALACIONES', 'AA1', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'MEDIDA_SEGURIDAD', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('CIERRE DE ESTABLECIMIENTO', 'AA2', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'MEDIDA_SEGURIDAD', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');


--mdi_maestro_columna ACCION_MEDIDA

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('SUSPENSIÓN PARCIAL DE ACTIVIDADES', 'AA1', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ACCION_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('SUSPENSIÓN DE REGISTRO DE HIDROCARBUROS', 'AA2', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ACCION_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

--mdi_maestro_columna NUMERO DE ANEXO

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 1', '1',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA002', null, SYSDATE, 'squito', '', '', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 2', '2',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA002', null, SYSDATE, 'squito', '', '', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 3', '3',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA002', null, SYSDATE , 'squito', '', '', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('1', '4',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA004', NULL, SYSDATE, 'squito', 'squito', '11.160.123.73', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('2', '5',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA004', NULL,SYSDATE, 'squito', 'squito', '11.160.123.73', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('3', '6',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA004', NULL, SYSDATE, 'squito', 'squito', '11.160.123.73', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 1', '7',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA003', null, SYSDATE, 'squito', '', '', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 2', '8',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA003', null, SYSDATE, 'squito', '', '', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 3', '9',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA003', null, SYSDATE, 'squito', '', '', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 1', '10',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA001', NULL, SYSDATE, 'squito', 'squito', '11.160.123.73', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 2', '11',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA001', NULL, SYSDATE, 'squito', 'squito', '11.160.123.73', '11.160.123.73', 'OBLIGACIONES', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('ANEXO 3', '12',  MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'TA001', NULL, SYSDATE, 'squito', 'squito', '11.160.123.73', '11.160.123.73', 'OBLIGACIONES', '1');


-- MDI_MAESTRO_COLUMNA ESCENARIO_MEDIDA


insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('REEMPLAZO, REUBICACION O MODIFICACION DE LOS TANQUES DE ALMACENAMIENTO', 'AA2', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('AUMENTO O REUBICACION DE SURTIDORES O DISPENSADORES DE DESPACHO', 'AA3', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('NO CUENTA CON INFORME TECNICO FAVORABLE DE MODIFICACION', 'AA4', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('NO CUENTA CON MODIFICACION DE REGISTRO DE HIDROCARBUROS', 'AA5', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('UN MINIMO DE DOS (02) EXTINTORES CONTRAINCENDIOS', 'AA6', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES DEBIDAMENTE OPERATIVOS Y VIGENTES', 'AA7', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES DE POLVO QUIMICO SECO MULTIPROPOSITO ABC', 'AA8', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES CON RATING NO MENOR A 20 A: 80 B:C', 'AA9', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES CON CERTIFICACION UL O FM', 'AA10', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

insert into mdi_maestro_columna (DESCRIPCION, CODIGO, ID_MAESTRO_COLUMNA, DOMINIO, FECHA_ACTUALIZACION, FECHA_CREACION, USUARIO_CREACION, USUARIO_ACTUALIZACION, TERMINAL_ACTUALIZACION, TERMINAL_CREACION, APLICACION, ESTADO)
values ('EXTINTORES UBICADOS EN LUGARES VISIBLES Y DE FACIL ACCESO', 'AA11', MDI_MAESTRO_COLUMNA_SEQ.NEXTVAL, 'ESCENARIO_MEDIDA', null, SYSDATE,  'squito', '', '', '11.160.123.73', 'MYC', '1');

