-- Fernando Costa
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Fernando', 'Costa', 'Moscol', 'fcosta@osinergmin.gob.pe', 'Costa Moscol Fernando', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'FCOSTA');

insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Marco Gonzales
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Marco', 'Gonzales', 'Peralta', 'mgonzales@osinergmin.gob.pe', 'Gonzales Peralta Marco', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'MGONZALES');

insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Tecnico Administrativo GFHL 03
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Tecnico Administrativo GFHL 03', 'Tecnico Administrativo GFHL 03', 'Tecnico Administrativo GFHL 03', 'TECADMGFHL03@osinergmin.gob.pe', 'Tecnico Administrativo GFHL 03', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'TECADMGFHL03');

insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Jorge Caballero
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Jorge Enrique', 'Caballero', 'Calle', 'JCABALLERO@osinergmin.gob.pe', 'Caballero Calle Jorge Enrique', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'JCABALLERO');

insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Victor Gonzales
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Victor Hugo', 'Gonzales', 'Vera', 'VGONZALES@osinergmin.gob.pe', 'Gonzales Vera Victor Hugo', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'VGONZALES');

insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Sandro Lopez
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Sandro Joe', 'Lopez', 'Collantes', 'SLOPEZ@osinergmin.gob.pe', 'Lopez Collantes Sandro Joe', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'SLOPEZ');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Ismael Gonzales
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Ismael Ivan', 'Gonzales', 'Romero', 'IGONZALES@osinergmin.gob.pe', 'Gonzales Romero Ismael Ivan', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'IGONZALES');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/

-- 	Quevedo Garcia, Magaly 
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Magaly', 'Quevedo', 'Garcia', 'MQUEVEDO@osinergmin.gob.pe', 'Quevedo Garcia Magaly', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'MQUEVEDO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Yopan Ramirez, Wilder
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Wilder', 'Yopan', 'Ramirez', 'WYOPAN@osinergmin.gob.pe', 'Yopan Ramirez Wilder', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'WYOPAN');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Lau Chu, Carolina 
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Carolina', 'Lau', 'Chu', 'CLAU@osinergmin.gob.pe', 'Lau Chu Carolina', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'CLAU');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Amemiya Hoshi, Felix 
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Felix', 'Amemiya', 'Hoshi', 'FAMEMIYA@osinergmin.gob.pe', 'Amemiya Hoshi Felix', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'FAMEMIYA');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Vera Cespedes, Rita Tania
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Rita Tania', 'Vera', 'Cespedes', 'RVERAC@osinergmin.gob.pe', 'Vera Cespedes Rita Tania', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'RVERAC');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Rebaza Castro, Edward Olver
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Edward Olver', 'Rebaza', 'Castro', 'EREBAZA@osinergmin.gob.pe', 'Rebaza Castro Edward Olver', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'EREBAZA');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Gomez Calero,Angelica Sulleyman
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Angelica Sulleyman', 'Gomez', 'Calero', 'AGOMEZ@osinergmin.gob.pe', 'Gomez Calero Angelica Sulleyman', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'AGOMEZ');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Martinez Pilar,Alan
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Alan', 'Martinez', 'Pilar', 'AMARTINEZP@osinergmin.gob.pe', 'Martinez Pilar Alan', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'AMARTINEZP');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Villena Rivera,Claudia Teresa
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Claudia Teresa', 'Villena', 'Rivera', 'CVILLENA@osinergmin.gob.pe', 'Villena Rivera Claudia Teresa', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'CVILLENA');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Vargas De La Cruz,Angelo Jhoseph
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Angelo Jhoseph', 'Vargas', 'De La Cruz', 'AVARGAS@osinergmin.gob.pe', 'Vargas De La Cruz Angelo Jhoseph', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'AVARGAS');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Castro Jurado, Diego Alonso
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Diego Alonso', 'Castro', 'Jurado', 'DCASTRO@osinergmin.gob.pe', 'Castro Jurado Diego Alonso', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'DCASTRO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Cersso Caso,Dante
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Dante', 'Cersso', 'Caso', 'DCERSSO@osinergmin.gob.pe', 'Cersso Caso Dante', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'DCERSSO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Estrada Vera,Enrique Oswaldo
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Enrique Oswaldo', 'Estrada', 'Vera', 'EESTRADA@osinergmin.gob.pe', 'Estrada Vera Enrique Oswaldo', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'EESTRADA');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- 	Delgado Guevara,Fredy Eberardo
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Fredy Eberardo', 'Delgado', 'Guevara', 'FDELGADO@osinergmin.gob.pe', 'Delgado Guevara Fredy Eberardo', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'FDELGADO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Mamani Ildefonso,Giovana Angelica
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Giovana Angelica', 'Mamani', 'Ildefonso', 'GMAMANI@osinergmin.gob.pe', 'Mamani Ildefonso Giovana Angelica', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'GMAMANI');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Diaz Flores, Jose Daniel
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Jose Daniel', 'Diaz', 'Flores', 'JDIAZF@osinergmin.gob.pe', 'Diaz Flores Jose Daniel', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'JDIAZF');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Bermeo Vargas, Marie Priscila 
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Marie Priscila', 'Bermeo', 'Vargas', 'MBERMEO@osinergmin.gob.pe', 'Bermeo Vargas Marie Priscila', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'MBERMEO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- GUEVARA ASCAN,CATHERINE
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'CATHERINE', 'GUEVARA', 'ASCAN', 'PROYDIP01@osinergmin.gob.pe', 'GUEVARA ASCAN CATHERINE', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'PROYDIP01');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Vereau Chavez,Robert John
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Robert John', 'Vereau', 'Chavez', 'RVEREAU@osinergmin.gob.pe', 'Vereau Chavez Robert John', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'RVEREAU');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Rengifo Ocrospoma,Brayan Smith
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Brayan Smith', 'Rengifo', 'Ocrospoma', 'BRENGIFO@osinergmin.gob.pe', 'Rengifo Ocrospoma Brayan Smith', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'BRENGIFO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Canelo Marcet, Jose Francisco
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Jose Francisco', 'Canelo', 'Marcet', 'JCANELO@osinergmin.gob.pe', 'Canelo Marcet Jose Francisco', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'JCANELO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Valer Morales, Aldo Edmundo
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Aldo Edmundo', 'Valer', 'Morales', 'AVALER@osinergmin.gob.pe', 'Valer Morales Aldo Edmundo', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'AVALER');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Martinez Estrella,Carlos Andres
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Carlos Andres', 'Martinez', 'Estrella', 'CMARTINEZ@osinergmin.gob.pe', 'Martinez Estrella Carlos Andres', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'CMARTINEZ');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Nonaka Ulloa,Cesar Enrique
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Cesar Enrique', 'Nonaka', 'Ulloa', 'CNONAKA@osinergmin.gob.pe', 'Nonaka Ulloa Cesar Enrique', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'CNONAKA');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Salazar Bellido, Israel Americo
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Israel Americo', 'Salazar', 'Bellido', 'ISALAZAR@osinergmin.gob.pe', 'Salazar Bellido Israel Americo', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'ISALAZAR');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Martinez Ramirez, Jaime Ernesto
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Jaime Ernesto', 'Martinez', 'Ramirez', 'JMARTINEZR@osinergmin.gob.pe', 'Martinez Ramirez Jaime Ernesto', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'JMARTINEZR');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Merino Novoa, Jorge Luis
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Jorge Luis', 'Merino', 'Novoa', 'JMERINO@osinergmin.gob.pe', 'Merino Novoa Jorge Luis', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'JMERINO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Villar Valladares, Jorge Humberto
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Jorge Humberto', 'Villar', 'Valladares', 'JVILLAR@osinergmin.gob.pe', 'Villar Valladares Jorge Humberto', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'JVILLAR');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Montoro Negrón,Luis Jaime
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Luis Jaime', 'Montoro', 'Negrón', 'LMONTORO@osinergmin.gob.pe', 'Montoro Negrón Luis Jaime', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'LMONTORO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Dioses Otero,Wilfredo
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Wilfredo', 'Dioses', 'Otero', 'WDIOSES@osinergmin.gob.pe', 'Dioses Otero Wilfredo', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'WDIOSES');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Gorriti Siappo,Zoila Paola
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Zoila Paola', 'Gorriti', 'Siappo', 'ZGORRITI@osinergmin.gob.pe', 'Gorriti Siappo Zoila Paola', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'ZGORRITI');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Sanchez Casabona, Glenda Fiorella
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Glenda Fiorella', 'Sanchez', 'Casabona', 'GSANCHEZ@osinergmin.gob.pe', 'Sanchez Casabona Glenda Fiorella', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'GSANCHEZ');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Lopez Ariadel, Ivan
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Ivan', 'Lopez', 'Ariadel', 'ILOPEZ@osinergmin.gob.pe', 'Lopez Ariadel Ivan', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'ILOPEZ');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Quiroz Gonzales, Jessica Judith
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Jessica Judith', 'Quiroz', 'Gonzales', 'JQUIROZ@osinergmin.gob.pe', 'Quiroz Gonzales Jessica Judith', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'JQUIROZ');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Quito Cortez,Sonia
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Sonia', 'Quito', 'Cortez', 'SQUITO@osinergmin.gob.pe', 'Quito Cortez Sonia', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'SQUITO');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/
-- Fox Joo, Elias Efrain
DECLARE
id_personal number;
BEGIN

select pgh_personal_seq.nextval into id_personal from dual;
  
insert into pgh_personal (ID_PERSONAL, ID_TIPO_DOCUMENTO_IDENTIDAD, NUMERO_DOC_IDENTIDAD, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO_ELECTRONICO, NOMBRE_COMPLETO, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_ROL, ID_CARGO, ID_SUPERVISORA_EMPRESA, ID_LOCADOR, ID_PERSONAL_SIGED, APLICACION, NOMBRE_USUARIO_SIGED)
values (id_personal, 1, 99999999, 'Elias Efrain', 'Fox', 'Joo', 'EFOX@osinergmin.gob.pe', 'Fox Joo Elias Efrain', '1', 'USU01', sysdate , '1.1.1.1', null, null, null, (SELECT R.ID_ROL FROM PGH_ROL R WHERE R.IDENTIFICADOR_ROL LIKE 'ESPECIALISTA' AND R.ESTADO = '1'),(SELECT C.ID_CARGO FROM PGH_CARGO C WHERE C.NOMBRE_CARGO LIKE 'ESPECIALISTA' AND C.ESTADO = '1'), null, null, null, 'MYC', 'EFOX');


insert into pgh_personal_unidad_organica (ID_PERSONAL_UNIDAD_ORGANICA, ID_PERSONAL, ID_UNIDAD_ORGANICA, FLAG_DEFAULT, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION)
values (pgh_personal_unidad_org_seq.nextval,id_personal, (SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.DESCRIPCION LIKE 'UPPD' AND UO.ESTADO = '1' and rownum=1 ), '1', '1', 'USU01', sysdate, '1.1.1.1', null, null,null);

END;
/