-- INSERTS REGISTROS CONFIGURACION ACTIVIDAD POR DIVISION
-- 063
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '063' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 048
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '048' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 145
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '145' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 061
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '061' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 049
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '049' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 021
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '021' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 705
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '705' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 020
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '020' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 118
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '118' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 011
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '011' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 040
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '040' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 042
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '042' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 035
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '035' AND A.AMBITO ='SFH' ), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 070
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '070' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 034
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '034' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 068
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '068' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 031
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '031' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 030
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '030' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 010
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '010' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 044
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '044' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 043
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '043' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 709
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL' AND UO.ESTADO='1' AND UO.NIVEL = '3'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '709' AND A.AMBITO ='SFH'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);

----------------------------------------------------------------------------------------------
--063
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '063' and ma.ambito = 'SFH';
--048
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '048' and ma.ambito = 'SFH';
--145
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '145' and ma.ambito = 'SFH';
--061
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '061' and ma.ambito = 'SFH';
--049
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '049' and ma.ambito = 'SFH';
--705
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '705' and ma.ambito = 'SFH';
--021
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '021' and ma.ambito = 'SFH';
--020
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '020' and ma.ambito = 'SFH';
--118
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '118' and ma.ambito = 'SFH';
--011
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '011' and ma.ambito = 'SFH';
--040
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '040' and ma.ambito = 'SFH';
--042
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '042' and ma.ambito = 'SFH';
--035
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '035' and ma.ambito = 'SFH';
--070
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '070' and ma.ambito = 'SFH';
--034
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '034' and ma.ambito = 'SFH';
--068
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '068' and ma.ambito = 'SFH';
--031
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '031' and ma.ambito = 'SFH';
--030
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '030' and ma.ambito = 'SFH';
--010
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '010' and ma.ambito = 'SFH';
--044
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '044' and ma.ambito = 'SFH';
--043
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '043' and ma.ambito = 'SFH';
--709
update mdi_actividad ma set ma.estado = '1' where ma.codigo = '709' and ma.ambito = 'SFH';

-------------------
--70
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '70';
--71
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '71';
--73
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '73';
--74
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '74';
--75
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '75';
--76
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '76';
--78
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '78';
--79
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '79';
--82
update mdi_actividad ma set ma.estado = '1' where ma.id_actividad = '82';


