-- INSERTS REGISTROS CONFIGURACION ACTIVIDAD POR DIVISION
-- 063
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '063'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 048
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '048'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 145
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '145'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 026
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '026'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 061
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '061'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 049
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '049'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 021
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '021' AND  A.ESTADO = '1'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 705
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '705'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 020
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '020' AND  A.ESTADO = '1'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 118
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '118'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 011
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '011' AND  A.ESTADO = '1'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 040
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '040'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 042
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '042'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 035
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '035'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 070
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '070'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 034
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '034'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 068
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '068'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 031
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '031' AND  A.ESTADO = '1'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 030
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '030' AND  A.ESTADO = '1'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 010
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '010' AND  A.ESTADO = '1'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 044
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '044'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 043
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '043'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);
-- 709
insert into pgh_cnf_act_uni_organica (ID_UNIDAD_ORGANICA, ID_ACTIVIDAD, ID_CNF_ACT_UNI_ORGANICA, ESTADO, USUARIO_CREACION, FECHA_CREACION, TERMINAL_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION, TERMINAL_ACTUALIZACION, ID_OBLIGACION_TIPO)
values ((SELECT UO.ID_UNIDAD_ORGANICA FROM MDI_UNIDAD_ORGANICA UO WHERE UO.SIGLA LIKE 'DSHL'), (SELECT A.ID_ACTIVIDAD FROM MDI_ACTIVIDAD A WHERE A.CODIGO = '709'), pgh_cnf_act_uni_organica_seq.nextval, '1', 'USU01', SYSDATE, '1.1.1.1', null, null, null, null);


