UPDATE NPS_INTEGRADO.MDI_MAESTRO_COLUMNA M
SET M.ESTADO = '0'
WHERE M.DOMINIO="PGH_OBLIG_CLASIF" AND M.APLICACION = "OBLIGACIONES" AND M.ID_MAESTRO_COLUMNA=203;

UPDATE NPS_INTEGRADO.MDI_MAESTRO_COLUMNA M
SET M.ESTADO = '0'
WHERE M.DOMINIO="PGH_OBLIG_CLASIF" AND M.APLICACION = "OBLIGACIONES" AND M.ID_MAESTRO_COLUMNA=204;

UPDATE NPS_INTEGRADO.MDI_MAESTRO_COLUMNA M
SET M.ESTADO = '0'
WHERE M.DOMINIO="PGH_OBLIG_CLASIF" AND M.APLICACION = "OBLIGACIONES" AND M.ID_MAESTRO_COLUMNA=205;

UPDATE NPS_INTEGRADO.MDI_MAESTRO_COLUMNA M
SET M.ESTADO = '0'
WHERE M.DOMINIO="PGH_OBLIG_CLASIF" AND M.APLICACION = "OBLIGACIONES" AND M.ID_MAESTRO_COLUMNA=210;

UPDATE NPS_INTEGRADO.MDI_MAESTRO_COLUMNA M
SET M.ESTADO = '0'
WHERE M.DOMINIO="PGH_OBLIG_CLASIF" AND M.APLICACION = "OBLIGACIONES" AND M.ID_MAESTRO_COLUMNA=213;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=1;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=2;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=5;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=6;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=7;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=8;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=9;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=11;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=12;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=13;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=14;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=15;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=16;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=17;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=18;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=19;

UPDATE NPS_INTEGRADO.PGH_OBLIGACION_TIPO T
SET T.ESTADO = '0'
WHERE T.ID_OBLIGACION_TIPO=20;