-- Modifica tipo de dato
alter table PGH_INFRACCION modify ID_DOCUMENTO_ADJUNTO null;

-- Incremento longitud campo CODIGO para relacion con campo DOMINIO
alter table MDI_MAESTRO_COLUMNA modify CODIGO VARCHAR2(20);

-- UNIDAD ORGANICA, NIVEL Y NOMBRE NIVEL
alter table mdi_unidad_organica add NIVEL number(10);
alter table mdi_unidad_organica add NOMBRE_NIVEL number(10);
comment on column mdi_unidad_organica.NIVEL is 'Numero de nivel de la Unidad Organica.';
comment on column mdi_unidad_organica.NOMBRE_NIVEL is 'Identificador del Nombre del nivel. MDI_MAESTRO_COLUMNA (Dominio NIVEL_UNIDAD_ORGA)';  

-- TABLAS PARA SUPERVISION MUESTRAL - INICIO
CREATE TABLE PGH_ESTRATO
(
	ID_ESTRATO           number(10) NOT NULL ,
	NOMBRE               VARCHAR2(20) NULL ,
	ESTADO               CHAR(1) NOT NULL ,
	FECHA_CREACION       DATE NOT NULL ,
	USUARIO_CREACION     VARCHAR2(38) NOT NULL ,
	TERMINAL_CREACION    VARCHAR(38) NOT NULL ,
	FECHA_ACTUALIZACION  DATE NULL ,
	USUARIO_ACTUALIZACION VARCHAR2(38) NULL ,
	TERMINAL_ACTUALIZACION VARCHAR2(38) NULL 
);
COMMENT ON TABLE PGH_ESTRATO IS 'Tabla que almacena los Estratos.';
COMMENT ON COLUMN PGH_ESTRATO.ID_ESTRATO IS 'Identificador principal de la Tabla PGH_ESTRATO.';
COMMENT ON COLUMN PGH_ESTRATO.NOMBRE IS 'Nombre del Estrato';
COMMENT ON COLUMN PGH_ESTRATO.ESTADO IS 'Indica si el registro se encuentra vigente: 1, no se encuentra vigente: 0.';
COMMENT ON COLUMN PGH_ESTRATO.FECHA_CREACION IS 'Fecha en la que se creó el registro (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_ESTRATO.USUARIO_CREACION IS 'Usuario creador del registro.';
COMMENT ON COLUMN PGH_ESTRATO.TERMINAL_CREACION IS 'Terminal de creación.';
COMMENT ON COLUMN PGH_ESTRATO.FECHA_ACTUALIZACION IS 'Fecha en la que se modificó el registro por última vez (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_ESTRATO.USUARIO_ACTUALIZACION IS 'Usuario que modificó el registro por última vez.';
COMMENT ON COLUMN PGH_ESTRATO.TERMINAL_ACTUALIZACION IS 'Terminal que modificó el registro por última vez.';
CREATE UNIQUE INDEX PGH_ESTR_ID_ESTR_IDX ON PGH_ESTRATO (ID_ESTRATO   ASC);
ALTER TABLE PGH_ESTRATO	ADD CONSTRAINT  PGH_ESTR_PK PRIMARY KEY (ID_ESTRATO);

CREATE TABLE PGH_ESTRATO_UBIGEO
(
	ID_ESTRATO_UBIGEO    number(10) NOT NULL ,
	ID_ESTRATO           number(10) NULL ,
	ID_DEPARTAMENTO      CHAR(2) NULL ,
	ID_PROVINCIA         CHAR(2) NULL ,
	ID_DISTRITO          CHAR(2) NULL ,
	ESTADO               CHAR(1) NOT NULL ,
	FECHA_CREACION       DATE NOT NULL ,
	USUARIO_CREACION     VARCHAR2(38) NOT NULL ,
	TERMINAL_CREACION    VARCHAR(38) NOT NULL ,
	FECHA_ACTUALIZACION  DATE NULL ,
	USUARIO_ACTUALIZACION VARCHAR2(38) NULL ,
	TERMINAL_ACTUALIZACION VARCHAR2(38) NULL 
);
COMMENT ON TABLE PGH_ESTRATO_UBIGEO IS 'Tabla que relaciona los Estratos y Ubigeos.';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.ID_ESTRATO_UBIGEO IS 'Identificador principal de la tabla PGH_ESTRATO_UBIGEO.';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.ID_ESTRATO IS 'Identificador principal de la Tabla PGH_ESTRATO.';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.ID_DEPARTAMENTO IS 'Código del Departamento';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.ID_PROVINCIA IS 'Código de la Provincia';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.ID_DISTRITO IS 'Código del Distrito';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.ESTADO IS 'Indica si el registro se encuentra vigente: 1, no se encuentra vigente: 0.';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.FECHA_CREACION IS 'Fecha en la que se creó el registro (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.USUARIO_CREACION IS 'Usuario creador del registro.';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.TERMINAL_CREACION IS 'Terminal de creación.';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.FECHA_ACTUALIZACION IS 'Fecha en la que se modificó el registro por última vez (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.USUARIO_ACTUALIZACION IS 'Usuario que modificó el registro por última vez.';
COMMENT ON COLUMN PGH_ESTRATO_UBIGEO.TERMINAL_ACTUALIZACION IS 'Terminal que modificó el registro por última vez.';
CREATE UNIQUE INDEX PGH_ESTR_UBIG_ID_ESTR_UBIG_IDX ON PGH_ESTRATO_UBIGEO (ID_ESTRATO_UBIGEO   ASC);
ALTER TABLE PGH_ESTRATO_UBIGEO ADD CONSTRAINT  PGH_ESTR_UBIG_PK PRIMARY KEY (ID_ESTRATO_UBIGEO);
ALTER TABLE PGH_ESTRATO_UBIGEO ADD CONSTRAINT PGH_ESTR_ESTR_UBIG_FK FOREIGN KEY (ID_ESTRATO) REFERENCES PGH_ESTRATO (ID_ESTRATO) ON DELETE SET NULL;
ALTER TABLE PGH_ESTRATO_UBIGEO ADD CONSTRAINT MDI_UBIG_ESTR_UBIG_FK FOREIGN KEY (ID_DEPARTAMENTO, ID_PROVINCIA, ID_DISTRITO) REFERENCES MDI_UBIGEO (ID_DEPARTAMENTO, ID_PROVINCIA, ID_DISTRITO) ON DELETE SET NULL;
-- TABLAS PARA SUPERVISION MUESTRAL - FIN

-- TABLA UBIGEO REGION - INICIO
CREATE TABLE PGH_UBIGEO_REGION
(
	ID_UBIGEO_REGION     number(10) NOT NULL ,
	ID_DEPARTAMENTO      CHAR(2) NULL ,
	ID_PROVINCIA         CHAR(2) NULL ,
	ID_DISTRITO          CHAR(2) NULL ,
	ID_REGION            NUMBER(10) NULL ,
	ESTADO               CHAR(1) NOT NULL ,
	FECHA_CREACION       DATE NOT NULL ,
	USUARIO_CREACION     VARCHAR2(38) NOT NULL ,
	TERMINAL_CREACION    VARCHAR(38) NOT NULL ,
	FECHA_ACTUALIZACION  DATE NULL ,
	USUARIO_ACTUALIZACION VARCHAR2(38) NULL ,
	TERMINAL_ACTUALIZACION VARCHAR2(38) NULL 
);
COMMENT ON TABLE PGH_UBIGEO_REGION IS 'Tabla que almacena la relacion entre UBIGEOS y REGIONES.';
COMMENT ON COLUMN PGH_UBIGEO_REGION.ID_UBIGEO_REGION IS 'Identificador principal de la tabla';
COMMENT ON COLUMN PGH_UBIGEO_REGION.ID_DEPARTAMENTO IS 'Código del Departamento';
COMMENT ON COLUMN PGH_UBIGEO_REGION.ID_PROVINCIA IS 'Código de la Provincia';
COMMENT ON COLUMN PGH_UBIGEO_REGION.ID_DISTRITO IS 'Código del Distrito';
COMMENT ON COLUMN PGH_UBIGEO_REGION.ID_REGION IS 'Identificador del registro en la entidad / tabla.  Secuencia: MDI_REGION_SEQ';
COMMENT ON COLUMN PGH_UBIGEO_REGION.ESTADO IS 'Indica si el registro se encuentra vigente: 1, no se encuentra vigente: 0.';
COMMENT ON COLUMN PGH_UBIGEO_REGION.FECHA_CREACION IS 'Fecha en la que se creó el registro (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_UBIGEO_REGION.USUARIO_CREACION IS 'Usuario creador del registro.';
COMMENT ON COLUMN PGH_UBIGEO_REGION.TERMINAL_CREACION IS 'Terminal de creación.';
COMMENT ON COLUMN PGH_UBIGEO_REGION.FECHA_ACTUALIZACION IS 'Fecha en la que se modificó el registro por última vez (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_UBIGEO_REGION.USUARIO_ACTUALIZACION IS 'Usuario que modificó el registro por última vez.';
COMMENT ON COLUMN PGH_UBIGEO_REGION.TERMINAL_ACTUALIZACION IS 'Terminal que modificó el registro por última vez.';
CREATE UNIQUE INDEX PGH_UBIG_REG_ID_UBIG_REG_IDX ON PGH_UBIGEO_REGION (ID_UBIGEO_REGION   ASC);
ALTER TABLE PGH_UBIGEO_REGION ADD CONSTRAINT  PGH_UBIG_REGI_PK PRIMARY KEY (ID_UBIGEO_REGION);
ALTER TABLE PGH_UBIGEO_REGION ADD CONSTRAINT MDI_UBIG_UBIG_REGI_FK FOREIGN KEY (ID_DEPARTAMENTO, ID_PROVINCIA, ID_DISTRITO) REFERENCES MDI_UBIGEO (ID_DEPARTAMENTO, ID_PROVINCIA, ID_DISTRITO) ON DELETE SET NULL;
ALTER TABLE PGH_UBIGEO_REGION ADD CONSTRAINT MDI_REGI_UBIG_REGI_FK FOREIGN KEY (ID_REGION) REFERENCES MDI_REGION (ID_REGION) ON DELETE SET NULL;
-- TABLA UBIGEO REGION - FIN

-- TABLA PGH_OBLIGACION_SUB_TIPO - INICIO
CREATE TABLE PGH_OBLIGACION_SUB_TIPO
(
	ID_OBLIGACION_SUB_TIPO NUMBER(10) NOT NULL ,
	NOMBRE               VARCHAR2(400) NULL ,
	ID_OBLIGACION_TIPO   NUMBER(10) NULL ,
	IDENTIFICADOR_SELECCION CHAR(1) NULL ,
	ESTADO               CHAR(1) NOT NULL ,
	USUARIO_CREACION     VARCHAR2(38) NOT NULL ,
	FECHA_CREACION       DATE NOT NULL ,
	TERMINAL_CREACION    VARCHAR(38) NOT NULL ,
	USUARIO_ACTUALIZACION VARCHAR2(38) NULL ,
	FECHA_ACTUALIZACION  DATE NULL ,
	TERMINAL_ACTUALIZACION VARCHAR2(38) NULL 
);
COMMENT ON TABLE PGH_OBLIGACION_SUB_TIPO IS 'Tabla que registra las obligaciones sub tipo.';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.ID_OBLIGACION_SUB_TIPO IS 'Identificador principal de la Tabla';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.NOMBRE IS 'Nombre de la Obligacion SubTipo';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.ID_OBLIGACION_TIPO IS 'Identificador principal de la Obligación Tipo, es un número correlativo.';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.IDENTIFICADOR_SELECCION IS 'Identificador para la seleccion muestral';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.ESTADO IS 'Indica si el registro se encuentra vigente: 1, no se encuentra vigente: 0.';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.USUARIO_CREACION IS 'Usuario creador del registro.';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.FECHA_CREACION IS 'Fecha en la que se creó el registro (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.TERMINAL_CREACION IS 'Terminal de creación.';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.USUARIO_ACTUALIZACION IS 'Usuario que modificó el registro por última vez.';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.FECHA_ACTUALIZACION IS 'Fecha en la que se modificó el registro por última vez (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_OBLIGACION_SUB_TIPO.TERMINAL_ACTUALIZACION IS 'Terminal que modificó el registro por última vez.';
CREATE UNIQUE INDEX PGH_OBLI_SUB_ID_OBLI_IDX ON PGH_OBLIGACION_SUB_TIPO (ID_OBLIGACION_SUB_TIPO   ASC);
ALTER TABLE PGH_OBLIGACION_SUB_TIPO ADD CONSTRAINT  PGH_OBLI_SUB_TIPO_PK PRIMARY KEY (ID_OBLIGACION_SUB_TIPO);
ALTER TABLE PGH_OBLIGACION_SUB_TIPO ADD CONSTRAINT PGH_OBLI_TIP_OBLI_SUB_TIPO_FK FOREIGN KEY (ID_OBLIGACION_TIPO) REFERENCES PGH_OBLIGACION_TIPO (ID_OBLIGACION_TIPO) ON DELETE SET NULL;
-- TABLA PGH_OBLIGACION_SUB_TIPO - FIN

-- CAMPO OBLIG_SUB_TIPO EN EXPEDIENTE - INICIO
ALTER TABLE PGH_EXPEDIENTE ADD (ID_OBLIGACION_SUB_TIPO NUMBER(10));
COMMENT ON COLUMN PGH_EXPEDIENTE.ID_OBLIGACION_SUB_TIPO IS 'Tabla que registra las obligaciones sub tipo';
ALTER TABLE PGH_EXPEDIENTE ADD CONSTRAINT PGH_OBLI_SUB_TIP_EXP FOREIGN KEY (ID_OBLIGACION_SUB_TIPO) REFERENCES PGH_OBLIGACION_SUB_TIPO (ID_OBLIGACION_SUB_TIPO) ON DELETE SET NULL;

-- CAMPO FLAG_MUESTRAL EN EXPEDIENTE - INICIO
ALTER TABLE PGH_EXPEDIENTE ADD (FLAG_MUESTRAL CHAR(1));
COMMENT ON COLUMN PGH_EXPEDIENTE.FLAG_MUESTRAL IS 'Indica si el registro proviene de Seleccion Muestral';

-- Tabla PGH_CONF_FILTRO_EMP_SUP para configuracion de Filtro x Empresa_Supervisora
CREATE TABLE PGH_CONF_FILTRO_EMP_SUP
(
	ID_FILTRO_EMP_SUP    NUMBER(10) NOT NULL ,
	ID_UNIDAD_ORGANICA   NUMBER(38) NOT NULL ,
	ID_FILTRO            NUMBER(10) NOT NULL ,
	ESTADO               CHAR(1) NOT NULL ,
	USUARIO_CREACION     VARCHAR2(38) NOT NULL ,
	FECHA_CREACION       DATE NOT NULL ,
	TERMINAL_CREACION    VARCHAR(38) NOT NULL ,
	USUARIO_ACTUALIZACION VARCHAR2(38) NULL ,
	FECHA_ACTUALIZACION  DATE NULL ,
	TERMINAL_ACTUALIZACION VARCHAR2(38) NULL 
);
COMMENT ON TABLE PGH_CONF_FILTRO_EMP_SUP IS 'Tabla que almacena los datos de configuracion de filtros de empresas supervisoras.';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.ID_FILTRO_EMP_SUP IS 'Identificador del registro en la entidad / tabla. Secuencia: PGH_CONF_FILTRO_EMP_SUP_SEQ.';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.ID_UNIDAD_ORGANICA IS 'Identificador de la Unidad Orgánica';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.ID_FILTRO IS 'Identificador del maestro columna FILTRO_EMP_SUP';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.ESTADO IS 'Indica si el registro se encuentra vigente: 1, no se encuentra vigente: 0.';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.USUARIO_CREACION IS 'Usuario creador del registro.';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.FECHA_CREACION IS 'Fecha en la que se creó el registro (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.TERMINAL_CREACION IS 'Terminal de creación.';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.USUARIO_ACTUALIZACION IS 'Usuario que modificó el registro por última vez.';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.FECHA_ACTUALIZACION IS 'Fecha en la que se modificó el registro por última vez (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_CONF_FILTRO_EMP_SUP.TERMINAL_ACTUALIZACION IS 'Terminal que modificó el registro por última vez.';
CREATE UNIQUE INDEX PGH_CONF_FILT_ID_EMP_IDX ON PGH_CONF_FILTRO_EMP_SUP (ID_FILTRO_EMP_SUP   ASC);
ALTER TABLE PGH_CONF_FILTRO_EMP_SUP ADD CONSTRAINT  PGH_CONF_FILT_PK PRIMARY KEY (ID_FILTRO_EMP_SUP);
ALTER TABLE PGH_CONF_FILTRO_EMP_SUP ADD CONSTRAINT MDI_UNI_ORG_CON_FIL_EMP_SUP_FK FOREIGN KEY (ID_UNIDAD_ORGANICA) REFERENCES MDI_UNIDAD_ORGANICA (ID_UNIDAD_ORGANICA) ON DELETE SET NULL;

-- Sequence para PGH_CONF_FILTRO_EMP_SUP
create sequence PGH_CONF_FILTRO_EMP_SUP_SEQ;

-- CREACION DE TABLA PGH_UNIDAD_OBLIGACION_SUB_TIPO
CREATE TABLE PGH_UNID_OBLI_SUB_TIPO
(
	ID_UNID_OBLI_SUB_TIPO NUMBER(10) NOT NULL ,
	ID_UNIDAD_SUPERVISADA NUMBER(10) NULL ,
	ID_OBLIGACION_SUB_TIPO NUMBER(10) NULL ,
	PERIODO              varchar2(10) NULL ,
	TIPO_SELECCION       numer(10) NULL ,
	FLAG_SUP_ORDEN_SERVICIO CHAR(1) NULL ,
	ESTADO               CHAR(1) NOT NULL ,
	USUARIO_CREACION     VARCHAR2(38) NOT NULL ,
	FECHA_CREACION       DATE NOT NULL ,
	TERMINAL_CREACION    VARCHAR(38) NOT NULL ,
	USUARIO_ACTUALIZACION VARCHAR2(38) NULL ,
	FECHA_ACTUALIZACION  DATE NULL ,
	TERMINAL_ACTUALIZACION VARCHAR2(38) NULL 
);

COMMENT ON TABLE PGH_UNID_OBLI_SUB_TIPO IS 'Tabla que almacena la relacion entre Unidad Supervisada y Obligacion Sub Tipo.';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.ID_UNID_OBLI_SUB_TIPO IS 'Identificador de la unidad obligacion sub tipo';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.ID_UNIDAD_SUPERVISADA IS 'Identificador del registro en la entidad / tabla.  Secuencia: MDI_UNIDAD_SUPERVISADA_SEQ';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.ID_OBLIGACION_SUB_TIPO IS 'Identificador principal de la Tabla';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.PERIODO IS 'Periodo de vigencia de la seleccion muestal';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.TIPO_SELECCION IS 'Identificador del maestro columna: Muestral,Contingencia o Asignacion';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.FLAG_SUP_ORDEN_SERVICIO IS 'Flag que indica si la unidad tiene una orden de servicio generada: 1: tiene , 0: no tiene';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.ESTADO IS 'Indica si el registro se encuentra vigente: 1, no se encuentra vigente: 0.';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.USUARIO_CREACION IS 'Usuario creador del registro.';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.FECHA_CREACION IS 'Fecha en la que se creó el registro (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.TERMINAL_CREACION IS 'Terminal de creación.';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.USUARIO_ACTUALIZACION IS 'Usuario que modificó el registro por última vez.';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.FECHA_ACTUALIZACION IS 'Fecha en la que se modificó el registro por última vez (Formato: DD/MM/YYYY hh:mm:ss).';
COMMENT ON COLUMN PGH_UNID_OBLI_SUB_TIPO.TERMINAL_ACTUALIZACION IS 'Terminal que modificó el registro por última vez.';

CREATE UNIQUE INDEX PGH_UNID_OBLI_ID_UNID_IDX ON PGH_UNID_OBLI_SUB_TIPO (ID_UNID_OBLI_SUB_TIPO   ASC);
ALTER TABLE PGH_UNID_OBLI_SUB_TIPO ADD CONSTRAINT PGH_UNID_OBLI_SUB_PK PRIMARY KEY (ID_UNID_OBLI_SUB_TIPO);
ALTER TABLE PGH_UNID_OBLI_SUB_TIPO
ADD CONSTRAINT MDI_UNID_SUPE_UNID_OBLI_ST_FK FOREIGN KEY (ID_UNIDAD_SUPERVISADA) REFERENCES MDI_UNIDAD_SUPERVISADA (ID_UNIDAD_SUPERVISADA) ON DELETE SET NULL;
ALTER TABLE PGH_UNID_OBLI_SUB_TIPO
ADD CONSTRAINT PGH_OBLI_ST_UNID_OBLI_ST_FK FOREIGN KEY (ID_OBLIGACION_SUB_TIPO) REFERENCES PGH_OBLIGACION_SUB_TIPO (ID_OBLIGACION_SUB_TIPO) ON DELETE SET NULL;

-- CREAR SECUENCIA PGH_OBLIGACION_SUB_TIPO
CREATE SEQUENCE PGH_OBLIGACION_SUB_TIPO_SEQ;
-- CREAR SECUENCIA PGH_UNIDAD_OBLIGACION_SUB_TIPO
CREATE SEQUENCE PGH_UNID_OBLI_SUB_TIPO_SEQ;
-- CREAR SECUENCIA PGH_ESTRATO_UBIGEO
CREATE SEQUENCE PGH_ESTRATO_UBIGEO_SEQ;

-- ALINEA SEQUENCES para inserts
-- mdi_maestro_columna_seq
DROP SEQUENCE "MDI_MAESTRO_COLUMNA_SEQ";
DECLARE
  V_VALOR    NUMBER;
  V_COMANDO VARCHAR2(4000);
BEGIN
    SELECT nvl(MAX(id_maestro_columna)+1,1) INTO V_VALOR  FROM mdi_maestro_columna;
    V_COMANDO:='CREATE SEQUENCE "MDI_MAESTRO_COLUMNA_SEQ"  START WITH '||V_VALOR||' INCREMENT BY 1  NOMAXVALUE  NOCACHE';
    DBMS_OUTPUT.PUT_LINE(V_COMANDO);
    EXECUTE IMMEDIATE V_COMANDO;
END;
/

-- mdi_unidad_organica
DROP SEQUENCE "MDI_UNIDAD_ORGANICA_SEQ";
DECLARE
  V_VALOR    NUMBER;
  V_COMANDO VARCHAR2(4000);
BEGIN
    SELECT nvl(MAX(ID_UNIDAD_ORGANICA)+1,1) INTO V_VALOR  FROM MDI_UNIDAD_ORGANICA;
    V_COMANDO:='CREATE SEQUENCE "MDI_UNIDAD_ORGANICA_SEQ"  START WITH '||V_VALOR||' INCREMENT BY 1  NOMAXVALUE  NOCACHE';
    DBMS_OUTPUT.PUT_LINE(V_COMANDO);
    EXECUTE IMMEDIATE V_COMANDO;
END;
/

-- PGH_CONF_FILTRO_EMP_SUP_SEQ
DROP SEQUENCE "PGH_CONF_FILTRO_EMP_SUP_SEQ";
DECLARE
  V_VALOR    NUMBER;
  V_COMANDO VARCHAR2(4000);
BEGIN
    SELECT nvl(MAX(ID_FILTRO_EMP_SUP)+1,1) INTO V_VALOR  FROM PGH_CONF_FILTRO_EMP_SUP;
    V_COMANDO:='CREATE SEQUENCE "PGH_CONF_FILTRO_EMP_SUP_SEQ"  START WITH '||V_VALOR||' INCREMENT BY 1  NOMAXVALUE  NOCACHE';
    DBMS_OUTPUT.PUT_LINE(V_COMANDO);
    EXECUTE IMMEDIATE V_COMANDO;
END;
/