ALTER TABLE PGH_DETALLE_BASE_LEGAL ADD ID_NRO_DISPOSICION NUMBER(10);
ALTER TABLE PGH_DETALLE_BASE_LEGAL ADD ID_TIPO_DISPOSICION NUMBER(10);
ALTER TABLE PGH_DETALLE_BASE_LEGAL ADD FLG_DISPOSICION CHAR(1);
ALTER TABLE PGH_OBLIGACION_TIPIFICACION ADD ID_ACTIVIDAD NUMBER(10);
ALTER TABLE PGH_OBLI_TIPI_CRITERIO ADD ID_ACTIVIDAD NUMBER(10);