CREATE TABLE PGH_INFRACCION
(
  ID_INFRACCION        NUMBER(10) NOT NULL ,
  ID_OBLIGACION        NUMBER(10) NOT NULL ,
  DESCRIPCION_INFRACCION VARCHAR2(500) NULL ,
  ID_DOCUMENTO_ADJUNTO NUMBER(10) NOT NULL ,
  ID_MEDIDA_SEGURIDAD_MAESTRO NUMBER(10) NULL ,
  ID_ACCION_MAESTRO    NUMBER(10) NULL ,
  ID_PADRE             NUMBER NULL ,
  COD_TRAZABILIDAD     VARCHAR2(20) NULL ,
  COD_ACCION           VARCHAR(1) NULL ,
  ESTADO               CHAR(1) NOT NULL ,
  USUARIO_CREACION     VARCHAR2(38) NOT NULL ,
  FECHA_CREACION       DATE NOT NULL ,
  TERMINAL_CREACION    VARCHAR(38) NOT NULL ,
  USUARIO_ACTUALIZACION VARCHAR2(38) NULL ,
  FECHA_ACTUALIZACION  DATE NULL ,
  TERMINAL_ACTUALIZACION VARCHAR2(38) NULL 
);

CREATE UNIQUE INDEX PGH_INFRACCION_IDX ON PGH_INFRACCION
(ID_INFRACCION   ASC);

ALTER TABLE PGH_INFRACCION
  ADD CONSTRAINT  PGH_INFRACCION_PK PRIMARY KEY (ID_INFRACCION);

CREATE  INDEX XIF1PGH_INFRACCION ON PGH_INFRACCION
(ID_OBLIGACION   ASC);

CREATE  INDEX XIF2PGH_INFRACCION ON PGH_INFRACCION
(ID_DOCUMENTO_ADJUNTO   ASC);

ALTER TABLE PGH_INFRACCION
  ADD (CONSTRAINT PGH_OBLI_INFR_FK FOREIGN KEY (ID_OBLIGACION) REFERENCES PGH_OBLIGACION (ID_OBLIGACION) ON DELETE SET NULL);

ALTER TABLE PGH_INFRACCION
  ADD (CONSTRAINT PGH_DOCU_ADJU_INFR_FK FOREIGN KEY (ID_DOCUMENTO_ADJUNTO) REFERENCES MDI_DOCUMENTO_ADJUNTO (ID_DOCUMENTO_ADJUNTO) ON DELETE SET NULL);

comment on table PGH_INFRACCION
  is 'Tabla que contiene las infracciones';
  
comment on column PGH_INFRACCION.ID_INFRACCION
  is 'Identificador de la Tabla infracción, es un número correlativo.';
  
comment on column PGH_INFRACCION.ID_OBLIGACION
  is 'Identificador principal de la Obligación, es un número correlativo.';
  
comment on column PGH_INFRACCION.DESCRIPCION_INFRACCION
  is 'Descripción de la Infracción.';
  
  
create sequence PGH_INFRACCION_SEQ
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
nocache;